FROM python:3.11-slim

WORKDIR /

COPY . .

RUN pip --upgrade pip

# install requirement
RUN pip install -r requirements.txt

EXPOSE 5000

# run the application: flask --app .\app\__init__.py run --reload --port 8080
CMD ["flask", "--app", "app.__init__", "run", "--reload"]