# Generated by Django 3.2 on 2023-12-11 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_book_uploader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
