# Generated by Django 3.2 on 2023-12-11 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_book_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='url',
            new_name='location_url',
        ),
    ]
