# Generated by Django 3.2 on 2023-12-11 05:47

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_auto_20231211_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=books.models.GenerateBookImagePath('book_images')),
        ),
        migrations.AlterField(
            model_name='book',
            name='location_url',
            field=models.FileField(blank=True, null=True, upload_to=books.models.GenerateBookImagePath('book_locations')),
        ),
    ]
