# Generated by Django 3.2 on 2023-12-11 05:53

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_auto_20231211_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=books.models.GenerateBookImagePath()),
        ),
        migrations.AlterField(
            model_name='book',
            name='location_url',
            field=models.FileField(blank=True, null=True, upload_to=books.models.GenerateBookImagePath()),
        ),
    ]
