# Generated by Django 3.2 on 2023-12-11 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_auto_20231211_0114'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='location_url',
            new_name='file',
        ),
    ]
