# Generated by Django 3.2 on 2023-12-11 08:29

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0015_rename_location_url_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, max_length=1000, null=True, upload_to=books.models.GenerateBookImagePath()),
        ),
    ]
