# Generated by Django 3.2 on 2023-12-11 08:50

import books.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0017_alter_book_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=books.models.GenerateBookImagePath()),
        ),
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=books.models.GenerateBookImagePath()),
        ),
    ]
