# Generated by Django 3.2 on 2023-12-11 01:44

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.FileField(blank=True, null=True, upload_to=users.models.GenerateAvatarPath()),
        ),
    ]
