# Generated by Django 3.2 on 2023-12-11 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_book'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='book',
        ),
    ]
