# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: DigitalBookHub CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
        python-version: [3.11]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Checkout to repository
      uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache-dependency-path: ./webapp/package-lock.json
        cache: 'npm'

    - name: Install dependencies
      run: |
        npm install

    - name: Build React App
      working-directory: ./webapp
      run: |
        npm run build

  test:
      runs-on: ubuntu-latest

      steps:
        - name: Checkout to repository
          uses: actions/checkout@v2

        - name: Setup Python
          uses: actions/setup-python@v2
          with:
            python-version: ${{ matrix.python-version }}

        - name: Install dependencies for FastAPI backend
          working-directory: backend
          run: |
            pip install -r requirements.txt

        - name: Run tests for FastAPI backend
          working-directory: backend
          run: |
            echo "backend build successful"