# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: DigitalBookHub CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: git fetch --depth=1 origin +refs/tags/*:refs/tags/* || true

      - name: Get the commit SHA
        id: commit_sha
        run: echo "::set-output name=sha::$(git rev-parse --short ${{ github.sha }})"

      - name: Build and push Docker image with dynamic tag
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          COMMIT_SHA: ${{ steps.commit_sha.outputs.sha }}
        run: |
          # Build and push Docker image with dynamic tag (commit SHA)
          docker build -t ruferdz/digital-book-hub:${COMMIT_SHA} -f Dockerfile .
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker push ruferdz/digital-book-hub:${COMMIT_SHA}